[package]
name = "buddha"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rand = { version = "0.8", features = ["small_rng"] }
png = "0.17"
structopt = { version = "0.3", default-features = false }
